services:
  backend:
    image: ghcr.io/bakseter/mandagsmiddag/backend:latest
    build: ./backend
    ports:
      - '8080:8080'
    environment:
      - DATABASE_HOST=database
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DEV=true
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    develop:
      watch:
        - action: sync
          path: ./static
          target: /app/static
        - action: sync
          path: ./templates
          target: /app/templates
        - action: rebuild
          path: '**/*.go'
          target: /app

  database:
    image: postgres:17
    env_file:
      - postgres.env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.6
    env_file: keycloak.env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8090:8080
    command:
      - start-dev