apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend
  namespace: mandagsmiddag
spec:
  entryPoints:
    - public
  routes:
    - kind: Rule
      match: Host(`backend.mandagsmiddag.bakseter.net`)
      services:
        - name: backend
          port: 8080
      middlewares:
        - name: forwardauth-public
          namespace: oauth2-proxy
