apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database
  namespace: mandagsmiddag
spec:
  instances: 1
  inheritedMetadata:
    labels:
      recurring-job.longhorn.io/hetzner-backup: enabled
  storage:
    size: 1Gi
