apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend
  namespace: mandagsmiddag
spec:
  entryPoints:
    - public
  routes:
    - kind: Rule
      match: Host(`mandagsmiddag.no`)
      middlewares:
        - name: authentik
          namespace: authentik
      services:
        - name: frontend
          port: http
