apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: frontend
  namespace: mandagsmiddag
spec:
  endpointSelector:
    matchLabels:
      app: frontend

  ingress:
    # Allow ingress from Traefik
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: traefik
            app.kubernetes.io/name: traefik
      toPorts:
        - rules:
            http: []
          ports:
            - port: '3000'
              protocol: TCP

  egress: [] # no egress allowed
