apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend
  namespace: mandagsmiddag
spec:
  entryPoints:
    - public
  routes:
    - kind: Rule
      match: Host(`mandagsmiddag.no`) && PathPrefix(`/api`)
      services:
        - name: mandagsmiddag-oauth2-proxy
          port: 80
