apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: backend
  namespace: mandagsmiddag
spec:
  endpointSelector:
    matchLabels:
      app: backend

  ingress:
    # Allow ingress from oauth2-proxy
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: oauth2-proxy
      toPorts:
        - rules:
            http:
              - path: '/api/.*'
          ports:
            - port: '8080'
              protocol: TCP

    # Allow ingress from Prometheus for metrics scraping
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
            app.kubernetes.io/name: prometheus
      toPorts:
        - rules:
            http:
              - path: '/metrics'
                method: 'GET'
          ports:
            - port: '8080'
              protocol: TCP

  egress:
    # Allow egress to kube-dns (needed for DNS resolution)
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: TCP
            - port: '53'
              protocol: UDP

    # Allow egress to database
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: mandagsmiddag-database
      toPorts:
        - ports:
            - port: '5432'
              protocol: TCP
