apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: database
  namespace: mandagsmiddag
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: database

  ingress:
    # Allow traffic from backend
    - fromEndpoints:
        - matchLabels:
            app: backend
      toPorts:
        - rules:
            http: []
          ports:
            - protocol: TCP
              port: '5432'

    # Allow ingress from CloudNativePG operator
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: cloudnative-pg
            k8s:io.kubernetes.pod.namespace: cnpg-system
      toPorts:
        - rules:
            http: []
          ports:
            - port: '8000'
              protocol: TCP
            - port: '5432'
              protocol: TCP
