apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: frontend
  namespace: mandagsmiddag
spec:
  endpointSelector:
    matchLabels:
      app: frontend

  ingress:
    # Allow ingress from oauth2-proxy
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: oauth2-proxy
      toPorts:
        - rules:
            http:
              - path: '/.*'
          ports:
            - port: '3000'
              protocol: TCP

  egress: [] # no egress allowed
